### ISSUE TITLE
Documentation / Quickstart

### ISSUE THREAD

**Issue by code-for-coffee** [gruntmonkeyLLC/viewport#1]
Hey @jasonearly -

In your `/docs/install.md` I'd like to suggest the following changes:

``` markdown
# Quickstart (for those with knowledge of Node)

**tl;dr**: [Download Viewport](https://github.com/gruntmonkeyLLC/viewport/archive/master.zip) and run `$ npm install --global gulp && npm install && gulp serve` in that directory to get started.

Open Chrome Device Toolbar and select iPad.
Command+Shift+M (Mac) or Ctrl+Shift+M (Windows, Linux)


-
## Installation 
To take advantage of Viewport you need to:
...
```

Also, in your `package.json` you can add a start script to run your Gulpfile:

``` json
"scripts": {
    "start": "gulp serve",
    "test": "gulp && git status | grep 'working directory clean' >/dev/null || (echo 'Please commit all changes generated by building'; exit 1)"
  },
```

By doing so, you can `npm install --global gulp && npm install && npm start` keeping commands simple and locked into the npm ecosystem (even though you're using Gulp).

**Comment by code-for-coffee** [comment]
I forgot to add - there isn't a direct link to the installation instructions from `http://viewport.gruntmonkey.com/`; I'd add one.

**Comment by jasonearly** [comment]
Cool thanks. I agree the landing site needs to be updated as well. It's in the works.
